name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  publish-packages:
    uses: ./.github/workflows/publish-lambda-layer.yaml
    with:
      layer-name: SUBSCRIPTION_common-layer
      python-version: 3.11
    secrets:
      aws-region: ap-southeast-1
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-subscription-function:
    needs: publish-packages
    uses: ./.github/workflows/build-lambda-python.yaml
    with:
      name: subscription-function
      lambda-function-name: SUBSCRIPTION_subscription-function
      lambda-layer-name: SUBSCRIPTION_common-layer
      region: ap-southeast-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-preprocess-accoms-function:
    needs: publish-packages
    uses: ./.github/workflows/build-lambda-python.yaml
    with:
      name: preprocess-accoms-function
      lambda-function-name: SUBSCRIPTION_preprocess-accoms-function
      lambda-layer-name: SUBSCRIPTION_common-layer
      region: ap-southeast-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-create-notification-function:
    needs: publish-packages
    uses: ./.github/workflows/build-lambda-python.yaml
    with:
      name: create-notification-function
      lambda-function-name: SUBSCRIPTION_create-notification-function
      lambda-layer-name: SUBSCRIPTION_common-layer
      region: ap-southeast-1
      uploads:
        functions/create-notification-function/static
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-send-email-function:
    needs: publish-packages
    uses: ./.github/workflows/build-lambda-python.yaml
    with:
      name: send-email-function
      lambda-function-name: SUBSCRIPTION_send-email-function
      lambda-layer-name: SUBSCRIPTION_common-layer
      region: ap-southeast-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}